-- \i /home/globi/aslot/sql/users.sql
-- \i /root/aslot/sql/users.sql

drop table if exists users cascade;
CREATE TABLE IF NOT EXISTS users(
id int generated by default as identity,
pwd VARCHAR (100) NOT NULL,
bname varchar(16) UNIQUE NOT NULL,
brole varchar(6) not null default 'non');

-- psql slot
-- alter table users add column dat jsonb not null default '{}';
-- update users set dat=jsonb_set(dat,'{btcw}','btcwallet');
-- update users set dat=jsonb_build_object('btcw','btcwallet');
-- update users set dat=jsonb_build_object('ltcw','ltcwallet'); reriwte
update users set dat=jsonb_insert(dat,'{btcw}','"btcwallet"');
update users set dat=jsonb_insert(dat,'{ethw}','"ethwallet"');
update users set dat=jsonb_insert(dat,'{ltcw}','"ltcwallet"');
update users set dat=dat #-'{btcw}';
update users set dat=dat #-'{ltcw}';
update users set dat=dat -'ethw';
update users set dat='{}';
