-- \i /home/globi/aslot/sql/users.sql
-- \i /root/aslot/sql/users.sql

drop table if exists users cascade;
CREATE TABLE IF NOT EXISTS users(
id int generated by default as identity,
pwd VARCHAR (100) NOT NULL,
bname varchar(16) UNIQUE NOT NULL,
brole varchar(6) not null default 'non');
